### ISSUE TITLE
ArialMT_Plain_24 has some issues with blynk or Node MCU

### ISSUE THREAD

**Issue by tzaroon** [ThingPulse/esp8266-oled-ssd1306#253] opened 2019-08-26 07:42 UTC
When I initialize "ArialMT_Plain_24" font size in my code my node mcu crashes instantly When I load the webserver.
I am using the following libraries in my code. 
```
#define BLYNK_PRINT Serial
#include <SoftwareSerial.h>
#include <EEPROM.h>

#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <WiFiClient.h>
#include <ESP8266WebServer.h>
#include "web_page.h"

//Temperature Sensor
#include <DHT.h>
```
other sizes are working fine... kindly help!!!!

**Comment by marcelstoer** [comment] 2019-08-26 20:29
Sorry, this is not a bug in this library and this is not support forum -> closing

Maybe try a forum at https://www.esp8266.com/viewforum.php?f=7 instead.

**Closed by marcelstoer** 2019-08-26 20:29 UTC
