### ISSUE TITLE
Rotation ?

### ISSUE THREAD

**Issue by vtomanov** [ThingPulse/esp8266-oled-ssd1306#227] opened 2018-11-10 00:38 UTC
Hello,

I want to use the display vertically ( e.g. 64x128) any idea how this can be done with the library ?

Thanks

**Comment by Joennuh** [comment] 2018-11-10 08:38
It would indeed be great to have the possibility to use the screen vertically.

**Comment by vtomanov** [comment] 2018-11-10 08:52
The Adafruit lib which is pretty the sane has Rotation which does exactly this - should easy to be added to this lib also.. in my new project the screen is vertical in the enclosure.

**Comment by captFuture** [comment] 2019-01-09 11:35
I was exactly searching for the same thing because i want to use a 128x64 screen vertically

**Comment by marcelstoer** [comment] 2019-01-22 22:14
Duplicate of #204

**Closed by marcelstoer** 2019-01-22 22:14 UTC
